# Generated by Django 6.0.4 on 2026-04-29 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0001_initial'),
        ('itinerary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='itinerary',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='budget', to='itinerary.itinerary'),
        ),
    ]
