<<<<<<< HEAD
# Generated by Django 6.0.4 on 2026-04-29 08:11
=======
# Generated by Django 6.0.4 on 2026-04-29 07:04
>>>>>>> a39b742ef2581b72a0cd62fcb37dcb1a444d17af

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Maps UML 'name: str'", max_length=200)),
                ('category', models.CharField(help_text="Maps UML 'category: str'", max_length=100)),
                ('location', models.CharField(help_text="Maps UML 'location: str'", max_length=255)),
                ('cost', models.IntegerField(default=0, help_text="Maps UML 'cost: int'")),
                ('date', models.DateTimeField(help_text="Maps UML 'date: DateTime'")),
                ('time', models.DateTimeField(help_text="Maps UML 'time: DateTime'. Warn: Duplicate timestamp info.")),
            ],
        ),
        migrations.CreateModel(
            name='EntertainmentEvent',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='itinerary.event')),
                ('description', models.TextField(help_text="Maps UML 'description: str'")),
            ],
            bases=('itinerary.event',),
        ),
        migrations.CreateModel(
            name='FoodEvent',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='itinerary.event')),
                ('menu', models.TextField(blank=True, help_text="Maps UML 'menu: str'. Using TextField for flexible input.", null=True)),
            ],
            bases=('itinerary.event',),
        ),
        migrations.CreateModel(
            name='TransportationEvent',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='itinerary.event')),
                ('type', models.IntegerField(choices=[(1, 'Flight'), (2, 'Train'), (3, 'Bus'), (4, 'Rental Car'), (5, 'Walk/Other')], help_text="Maps UML 'type: int'")),
            ],
            bases=('itinerary.event',),
        ),
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Maps UML 'name: str'", max_length=200)),
                ('trip_destination', models.CharField(help_text="Maps UML 'trip_destination: str'", max_length=255)),
                ('start_date', models.DateTimeField(help_text="Maps UML 'start_date: DateTime'")),
                ('end_date', models.DateTimeField(help_text="Maps UML 'end_date: DateTime'")),
                ('number_of_participants', models.PositiveIntegerField(default=1, help_text="Maps UML 'number_of_participants: int'")),
                ('itinerary_events', models.IntegerField(default=0, help_text="Maps UML 'itinerary_events: int'. Warn: Static field, should be derived.")),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itineraries', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='itinerary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='itinerary.itinerary'),
=======
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=50)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('destination', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itineraries', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('current_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('itinerary', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='budget', to='itinerary.itinerary')),
            ],
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('message', models.TextField()),
                ('type', models.CharField(choices=[('reminder', 'Reminder'), ('warning', 'Warning'), ('info', 'Info')], default='info', max_length=50)),
                ('is_read', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to=settings.AUTH_USER_MODEL)),
                ('itinerary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='itinerary.itinerary')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('flight', 'Flight'), ('hotel', 'Hotel'), ('food', 'Food'), ('activity', 'Activity'), ('transport', 'Transport'), ('other', 'Other')], default='other', max_length=50)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('itinerary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='itinerary.itinerary')),
                ('place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='itinerary.place')),
            ],
            options={
                'ordering': ['start_datetime', 'order'],
            },
>>>>>>> a39b742ef2581b72a0cd62fcb37dcb1a444d17af
        ),
    ]
