# Generated by Django 6.0.4 on 2026-04-29 08:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Maps UML 'name: str'", max_length=200)),
                ('category', models.CharField(help_text="Maps UML 'category: str'", max_length=100)),
                ('location', models.CharField(help_text="Maps UML 'location: str'", max_length=255)),
                ('cost', models.IntegerField(default=0, help_text="Maps UML 'cost: int'")),
                ('date', models.DateTimeField(help_text="Maps UML 'date: DateTime'")),
                ('time', models.DateTimeField(help_text="Maps UML 'time: DateTime'. Warn: Duplicate timestamp info.")),
            ],
        ),
        migrations.CreateModel(
            name='EntertainmentEvent',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='itinerary.event')),
                ('description', models.TextField(help_text="Maps UML 'description: str'")),
            ],
            bases=('itinerary.event',),
        ),
        migrations.CreateModel(
            name='FoodEvent',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='itinerary.event')),
                ('menu', models.TextField(blank=True, help_text="Maps UML 'menu: str'. Using TextField for flexible input.", null=True)),
            ],
            bases=('itinerary.event',),
        ),
        migrations.CreateModel(
            name='TransportationEvent',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='itinerary.event')),
                ('type', models.IntegerField(choices=[(1, 'Flight'), (2, 'Train'), (3, 'Bus'), (4, 'Rental Car'), (5, 'Walk/Other')], help_text="Maps UML 'type: int'")),
            ],
            bases=('itinerary.event',),
        ),
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Maps UML 'name: str'", max_length=200)),
                ('trip_destination', models.CharField(help_text="Maps UML 'trip_destination: str'", max_length=255)),
                ('start_date', models.DateTimeField(help_text="Maps UML 'start_date: DateTime'")),
                ('end_date', models.DateTimeField(help_text="Maps UML 'end_date: DateTime'")),
                ('number_of_participants', models.PositiveIntegerField(default=1, help_text="Maps UML 'number_of_participants: int'")),
                ('itinerary_events', models.IntegerField(default=0, help_text="Maps UML 'itinerary_events: int'. Warn: Static field, should be derived.")),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itineraries', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='itinerary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='itinerary.itinerary'),
        ),
    ]
